FROM python:3.6-alpine 
MAINTAINER oraclegao@126.com

USER root

RUN set -xe \
    && apk add --no-cache --virtual .build-deps \
                                    curl \
                                    git \
    && pip install git+https://github.com/scrapy/scrapy.git \
                   git+https://github.com/scrapy/scrapyd.git \
                   git+https://github.com/scrapy/scrapyd-client.git \
                   git+https://github.com/scrapinghub/scrapy-splash.git \
                   git+https://github.com/scrapinghub/scrapyrt.git \
                   git+https://github.com/python-pillow/Pillow.git \
                   git+https://github.com/confluentinc/confluent-kafka-python \
    && curl -sSL https://github.com/scrapy/scrapy/raw/master/extras/scrapy_bash_completion -o /etc/bash_completion.d/scrapy_bash_completion \
    && echo 'source /etc/bash_completion.d/scrapy_bash_completion' >> /root/.bashrc \
    && apk del .build-deps

COPY ./scrapyd.conf /etc/scrapyd/

EXPOSE 6800

CMD ["scrapyd", "--pidfile="]
