version: '2'

services:
  nginx:
    restart: always
    image: nginx:stable
    ports:
      - ${PORT}:80
    volumes:
      - ${WWW_PATH}:/var/www/html
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    working_dir: /var/www/html
    user: root
    depends_on:
      - php-fpm
    environment:
      TZ: Asia/Shanghai
    networks:
      - laravel
    logging:
      options:
        max-size: 10mb

  php-fpm:
    restart: always
    image: ${LARAVEL_IMAGE}
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${WWW_PATH}:/var/www/html
    working_dir: /var/www/html
    user: root
    networks:
      - laravel
    logging:
       options:
         max-size: 10mb

networks:
  laravel:
