#docker 1.10.1
#docker-compose: 1.6.2

version: '2'

services:
  cas-server:
    restart: always
    image: ${RC_BUILD_DOCKER_IMAGE}
    ports:
      - 8443:8443
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
    environment:
      cas.server.name: https://10.1.10.20:8443
      cas.server.prefix: https://10.1.10.20:8443/cas
      cas.adminPagesSecurity.ip: 10.1.50.54
      CAS_DATABASE_HOST: 10.1.10.20
      CAS_DATABASE_PORT: 23306
    logging:
       options:
         max-size: 1g

  cas-server-dev:
    image: apereo/cas:v5.0.0
    ports:
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${USER_HOME_PATH}/.m2:/root/.m2
      - ${DEV_DATA_PATH}/etc/cas:/cas-overlay/etc/cas
      - ${DEV_DATA_PATH}/src:/cas-overlay/src
      - ${DEV_DATA_PATH}/pom.xml:/cas-overlay/pom.xml
    logging:
      options:
        max-size: 1g
