version: '3.2'

services:
  netdata:
    image: netdata/netdata:${NETDATA_IMAGE_TAG:-latest-amd64}
    ports:
      - ${NETDATA_PORT:-19999}:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: 10mb
