version: '3.2'

services:
  mysql:
    image: mysql:${MYSQL_IMAGE_TAG:-5.7}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ${MYSQL_DATA_PATH:-./data/mysql/}:/var/lib/mysql/
      - ${MYSQL_INIT_SQL_PATH:-./conf/sql/}:/docker-entrypoint-initdb.d/:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: ${MSQL_SCHEMA:-helloworld}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-passw0rd}
    command: --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --default-time_zone='+8:00'
    logging:
      options:
        max-size: 10mb
