version: '3.2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-80}:80
      - ${NGINX_SSL_PORT:-443}:443
    volumes:
      - ${NGINX_WWW_PATH:-./data/www}:/www/
      - ${NGINX_CONF_PATH:-./conf/nginx}:/etc/nginx/conf.d/
      - ${NGINX_CERT_PATH:-./cert/nginx}:/etc/nginx/cert/
    working_dir: /www
    environment:
      TZ: Asia/Shanghai
    logging:
      options:
        max-size: 10mb
