version: '3.2'

services:
  portainer:
    image: portainer/portainer:${PORTAINER_IMAGE_TAG:-latest}
    ports:
      - ${PORTAINER_PORT:-9000}:9000
    volumes:
      - ${PORTAINER_DATA_PATH:-./data/portainer}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: 10mb
