---
- name: Copy docker install script
  copy: 
    src: docker-install.sh
    dest: /tmp
    mode: 0755

- name: install docker
  shell: /tmp/docker-install.sh

- name: clean up docker install script
  shell: rm -rf /tmp/docker-install.sh
