version: '3.2'

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 8000:8000
      - 9000
    volumes:
      - ${DATA_PATH}:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_OPEN=true
      - DRONE_DEBUG=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_RPC_DEBUG=true
      - DRONE_GOGS_DEBUG=true
      - DRONE_STASH_DEBUG=true
      - TZ=Asia/Shanghai
      - DRONE_GOGS=true
      - DRONE_GOGS_SERVER=http://172.17.137.3:12306
      - DRONE_USER_CREATE=username:admin,admin:true
      - DRONE_ADMIN=admin
      - DRONE_SECRET=changit
      - DRONE_RPC_SECRET=changeit
      - DRONE_SERVER_HOST=drone.pplm.fun
      - DRONE_SERVER_PORT=:8000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_PROVIDER=gogs
        #   - DRONE_DATABASE_DRIVER=mysql
        #   - DRONE_DATABASE_DATASOURCE=root:123456@tcp(ip:3306)/drone?parseTime=true

  drone-agent:
    image: drone/agent:latest
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=true
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=changeit

