version: '3.2'

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 8000:80
      - 8001:9000
    volumes:
      - ${DRONE_DATA_PATH}:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - DRONE_GITHUB_CLIENT_ID=
      - DRONE_GITHUB_CLIENT_SECRET=
      - DRONE_SERVER_PROTO=http
      - DRONE_LOGS_DEBUG=true
      - DRONE_RPC_DEBUG=true
      - DRONE_STASH_DEBUG=true
      - DRONE_USER_CREATE=username:admin,admin:true
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_SERVER_HOST=120.77.176.165:8000
      - DRONE_GIT_ALWAYS_AUTH=false
 
  drone-agent:
    image: drone/agent:latest
    ports:
      - 8100:3000
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RUNNER_NAME=da1
      - DRONE_DEBUG=true
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_RPC_PROTO=http

  drone-runner-ssh:
    image: drone/drone-runner-ssh:linux-amd64
    ports:
      - 8200:3000
    depends_on:
      - drone-server
    environment:
      - DRONE_RUNNER_NAME=drs1
      - DRONE_DEBUG=true
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_RPC_PROTO=http

