version: '3.1'

services:
  wordpress:
    restart: always
    image: nginx:alpine
    links:
      - wordpress-fpm:wordpress-fpm
    ports: 
      - ${WP_PORT}:80
    volumes:
      - ${DEPLOY_HOME}/web:/www
      - ${CONFIG_PATH}:/etc/nginx/conf.d/
    logging:
       options:
         max-size: 20mb

  wordpress-fpm:
    restart: always
    image: wordpress:5.2.3-php7.2-fpm-alpine
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: passw0rd
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: WP_
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - ${DEPLOY_HOME}/web:/var/www/html    
#     - ${WORDPRESS_DEPLOY_HOME}/php/php.ini:/usr/local/etc/php/php.ini
    logging:
       options:
         max-size: 20mb

  db:
    restart: always
    image: mysql:5.7.27
    ports:
      - ${DB_PORT}:3306 
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - ${DEPLOY_HOME}/db:/var/lib/mysql
    logging:
       options:
         max-size: 20mb
