version: '2'
services:
  nexus3:
    restart: always
    image: sonatype/nexus3:3.14.0 
    user: root
    ports:
      - ${PORT}:8081
    volumes:
      - ${DATA_PATH}:/nexus-data
    environment:
      TZ: Asia/Shanghai
    logging:
      options:
        max-size: 10mb
