version: '2'

services:
  mysql:
    restart: always
    image: mysql:${IMAGE_VERSION}
    ports:
      - ${PORT}:3306
    volumes:
      - ${DATA_PATH}:/var/lib/mysql
      - ${INIT_DATABASE_PATH}:/docker-entrypoint-initdb.d:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: ${SCHEMA}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    logging:
      options:
        max-size: 10mb
