version: '3.2'

services:
  redis:
    image: redis:${REDIS_IMAGE_TAG:-5-alpine}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ${REDIS_CONF_PATH:-./conf/redis}:/usr/local/etc/redis
      - ${REDIS_DATA_PATH:-./data/redis}:/data
    command: /usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: 10mb

  redis-cli:
    image: ${REDIS_IMAGE:-redis:5-alpine}
    command: redis-cli -h redis
    logging:
      options:
        max-size: 10mb
