version: '3'
services:
  netdata:
    restart: always
    image: netdata/netdata:latest-amd64
    hostname: netdata
    ports:
      - ${PORT}:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
